[build]
  command = "npm run build:sls"
  publish = "dist/netlify-serverless/browser"

# any additional redirects for the site should come *before* this one
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/angular-builder"
  status = 200

[functions]
included_files=["dist/netlify-serverless/browser/index.html"]
node_bundler="esbuild"

[[plugins]]
  package = "../"
  [plugins.inputs]
  projectName = "angular-bfdx"